version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: 
          name: Install Hasura CLI
          command: curl -L https://cli.hasura.io/install.sh | bash
      - run: 
          name: Apply migration
          command: hasura migrate apply --endpoint=${HASURA_ENDPOINT} --admin-secret=${HASURA_GRAPHQL_ADMIN_SECRET}     
